/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.GUI;

import cr.ac.ucr.Domain.Agent;
import cr.ac.ucr.Logic.ListException.ListException;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author deltadragon
 */
public class CRUDs extends javax.swing.JFrame {

    public CRUDs() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_Cancel = new javax.swing.JButton();
        JL_fondo = new javax.swing.JLabel();
        JM_Cruds = new javax.swing.JMenuBar();
        JM_Driver = new javax.swing.JMenu();
        JMI_InsertDriver = new javax.swing.JMenuItem();
        JM_Restaurant = new javax.swing.JMenu();
        JMI_InsertRestaurant = new javax.swing.JMenuItem();
        JM_Agent = new javax.swing.JMenu();
        JMI_InsertAgent = new javax.swing.JMenuItem();
        JM_Product = new javax.swing.JMenu();
        JMI_InsertProduct = new javax.swing.JMenuItem();
        JM_Administrator = new javax.swing.JMenu();
        JMI_InsertAdministrator = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Cancel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        JB_Cancel.setForeground(new java.awt.Color(204, 204, 5));
        JB_Cancel.setText("Cancel");
        JB_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        JL_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/ucr/Img/admin.jpg"))); // NOI18N
        getContentPane().add(JL_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));

        JM_Driver.setText("Driver");

        JMI_InsertDriver.setText("Insert");
        JMI_InsertDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_InsertDriverActionPerformed(evt);
            }
        });
        JM_Driver.add(JMI_InsertDriver);

        JM_Cruds.add(JM_Driver);

        JM_Restaurant.setText("Restaurant");
        JM_Restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_RestaurantActionPerformed(evt);
            }
        });

        JMI_InsertRestaurant.setText("Insert");
        JMI_InsertRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_InsertRestaurantActionPerformed(evt);
            }
        });
        JM_Restaurant.add(JMI_InsertRestaurant);

        JM_Cruds.add(JM_Restaurant);

        JM_Agent.setText("Agent");
        JM_Agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_AgentActionPerformed(evt);
            }
        });

        JMI_InsertAgent.setText("Insert");
        JMI_InsertAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_InsertAgentActionPerformed(evt);
            }
        });
        JM_Agent.add(JMI_InsertAgent);

        JM_Cruds.add(JM_Agent);

        JM_Product.setText("Product");
        JM_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_ProductActionPerformed(evt);
            }
        });

        JMI_InsertProduct.setText("Insert");
        JMI_InsertProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_InsertProductActionPerformed(evt);
            }
        });
        JM_Product.add(JMI_InsertProduct);

        JM_Cruds.add(JM_Product);

        JM_Administrator.setText("Administrator");
        JM_Administrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_AdministratorActionPerformed(evt);
            }
        });

        JMI_InsertAdministrator.setText("Insert");
        JMI_InsertAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_InsertAdministratorActionPerformed(evt);
            }
        });
        JM_Administrator.add(JMI_InsertAdministrator);

        JM_Cruds.add(JM_Administrator);

        jMenu1.setText("Clients");

        jMenuItem1.setText("Update/Delete Client");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        JM_Cruds.add(jMenu1);

        setJMenuBar(JM_Cruds);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_InsertDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_InsertDriverActionPerformed
        InsertDriver id;
        
        
            id = new InsertDriver();
            id.setVisible(true);
       
        
    }//GEN-LAST:event_JMI_InsertDriverActionPerformed

    private void JM_RestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_RestaurantActionPerformed

    }//GEN-LAST:event_JM_RestaurantActionPerformed

    private void JM_AgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_AgentActionPerformed

    }//GEN-LAST:event_JM_AgentActionPerformed

    private void JM_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_ProductActionPerformed

    }//GEN-LAST:event_JM_ProductActionPerformed

    private void JM_AdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_AdministratorActionPerformed

    }//GEN-LAST:event_JM_AdministratorActionPerformed

    private void JMI_InsertRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_InsertRestaurantActionPerformed
        InsertRestaurant ir;
       
            ir = new InsertRestaurant();
               ir.setVisible(true);
       
       
        this.dispose();
     
    }//GEN-LAST:event_JMI_InsertRestaurantActionPerformed

    private void JMI_InsertAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_InsertAgentActionPerformed
        InsertAgent as;
        
            as = new InsertAgent();
             as.setVisible(true);
        
         
        this.dispose();
       
    }//GEN-LAST:event_JMI_InsertAgentActionPerformed

    private void JMI_InsertProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_InsertProductActionPerformed
        InsertProduct ip;
        
            ip = new InsertProduct();
            ip.setVisible(true);
        
        
        this.dispose();
        
    }//GEN-LAST:event_JMI_InsertProductActionPerformed

    private void JMI_InsertAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_InsertAdministratorActionPerformed
        InsertAdministrator ia;
        
            ia = new InsertAdministrator();
             ia.setVisible(true);
       
        this.dispose();
       
    }//GEN-LAST:event_JMI_InsertAdministratorActionPerformed

    private void JB_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_JB_CancelActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Cancel;
    private javax.swing.JLabel JL_fondo;
    private javax.swing.JMenuItem JMI_InsertAdministrator;
    private javax.swing.JMenuItem JMI_InsertAgent;
    private javax.swing.JMenuItem JMI_InsertDriver;
    private javax.swing.JMenuItem JMI_InsertProduct;
    private javax.swing.JMenuItem JMI_InsertRestaurant;
    private javax.swing.JMenu JM_Administrator;
    private javax.swing.JMenu JM_Agent;
    private javax.swing.JMenuBar JM_Cruds;
    private javax.swing.JMenu JM_Driver;
    private javax.swing.JMenu JM_Product;
    private javax.swing.JMenu JM_Restaurant;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
