/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.GUI;

import cr.ac.ucr.Domain.Order;

/**
 *
 * @author deltadragon
 */
public class OrderCompleteInformation extends javax.swing.JFrame {

    public OrderCompleteInformation() {
        initComponents();
    }

    public OrderCompleteInformation(String client, String numOrder, String agent, String date, String province, String driver,
            String restaurant, String product, String quantity, String amount) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.JT_Cliente.setText(client);
        this.JT_NumOrder.setText(numOrder);
        this.JT_Agent.setText(agent);
        this.JT_Date.setText(date);
        this.JT_Province.setText(province);
        this.JT_Driver.setText(driver);
        this.JT_Restaurant.setText(restaurant);
        this.JT_Product.setText(product);
        this.JT_Quantity.setText(quantity);
        this.JT_Amount.setText(amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JT_Cliente = new javax.swing.JLabel();
        JT_NumOrder = new javax.swing.JLabel();
        JT_Agent = new javax.swing.JLabel();
        JT_Date = new javax.swing.JLabel();
        JT_Province = new javax.swing.JLabel();
        JT_Driver = new javax.swing.JLabel();
        JT_Restaurant = new javax.swing.JLabel();
        JT_Product = new javax.swing.JLabel();
        JT_Quantity = new javax.swing.JLabel();
        JT_Amount = new javax.swing.JLabel();
        JB_cancel = new javax.swing.JButton();
        JL_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 5));
        jLabel2.setText("Information of Order");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, 30));

        jLabel3.setForeground(new java.awt.Color(204, 204, 5));
        jLabel3.setText("Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 5));
        jLabel4.setText("Number of order");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 5));
        jLabel5.setText("Agent");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 5));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 204, 5));
        jLabel7.setText("Province");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 275, -1, 10));

        jLabel8.setForeground(new java.awt.Color(204, 204, 5));
        jLabel8.setText("Restaurant");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 204, 5));
        jLabel9.setText("Driver");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 40, 10));

        jLabel1.setForeground(new java.awt.Color(204, 204, 5));
        jLabel1.setText("Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel10.setForeground(new java.awt.Color(204, 204, 5));
        jLabel10.setText("Quantity");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel11.setForeground(new java.awt.Color(204, 204, 5));
        jLabel11.setText("Amount");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        JT_Cliente.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, 20));

        JT_NumOrder.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_NumOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, 20));

        JT_Agent.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Agent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 210, 20));

        JT_Date.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 210, 20));

        JT_Province.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Province, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 20));

        JT_Driver.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 210, 20));

        JT_Restaurant.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Restaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 375, 210, 20));

        JT_Product.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 210, 20));

        JT_Quantity.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 210, 20));

        JT_Amount.setForeground(new java.awt.Color(204, 204, 5));
        getContentPane().add(JT_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 210, 20));

        JB_cancel.setForeground(new java.awt.Color(204, 204, 5));
        JB_cancel.setText("Regresar");
        JB_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(JB_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 10, 80, -1));

        JL_Fondo.setForeground(new java.awt.Color(204, 204, 5));
        JL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/ucr/Img/admin.jpg"))); // NOI18N
        getContentPane().add(JL_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_JB_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderCompleteInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderCompleteInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderCompleteInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderCompleteInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderCompleteInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_cancel;
    private javax.swing.JLabel JL_Fondo;
    private javax.swing.JLabel JT_Agent;
    private javax.swing.JLabel JT_Amount;
    private javax.swing.JLabel JT_Cliente;
    private javax.swing.JLabel JT_Date;
    private javax.swing.JLabel JT_Driver;
    private javax.swing.JLabel JT_NumOrder;
    private javax.swing.JLabel JT_Product;
    private javax.swing.JLabel JT_Province;
    private javax.swing.JLabel JT_Quantity;
    private javax.swing.JLabel JT_Restaurant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
